const values = [
  'nova-3-general',
  'nova-3-medical',
  'nova-2-general',
  'nova-2-meeting',
  'nova-2-phonecall',
  'nova-2-finance',
  'nova-2-conversationalai',
  'nova-2-voicemail',
  'nova-2-video',
  'nova-2-medical',
  'nova-2-drivethru',
  'nova-2-automotive',
  'nova-2-atc',
  'nova-general',
  'nova-phonecall',
  'nova-medical',
  'enhanced-general',
  'enhanced-meeting',
  'enhanced-phonecall',
  'enhanced-finance',
  'base-general',
  'base-meeting',
  'base-phonecall',
  'base-finance',
  'base-conversationalai',
  'base-voicemail',
  'base-video',
  'whisper-tiny',
  'whisper-base',
  'whisper-small',
  'whisper-medium',
  'whisper-large',
];

export const models = values.map((value) => ({
  value,
  label: 'Deepgram',
}));
