name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    env:
      BACKEND_IMAGE: agentvoiceresponse/avr-app-backend
      FRONTEND_IMAGE: agentvoiceresponse/avr-app-frontend
    steps:
      - uses: actions/checkout@v2

      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $username -p $password 

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ steps.package-version.outputs.current-version}}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ steps.package-version.outputs.current-version}}
